### PR TITLE
Fixes for issue 299

### LINKED ISSUE #299: how-to-use-bevespi-inhaler layout and glitches
image

(a) The shape design should be there (b) Text alignment 
issue & it should be in centre (c) That image should not appear there, as 
per bevespi please make it aligned after some content (d) Text is moved to
left side. (e) Bullets are moved to left, it should be aligned as per bevespi 
(f) The video should be aligned & optimised as per bevespi. (g) Whole 
content is moved to left, it should be aligned as per bevespi (h) Please 
make align the + btton with the text (i) Space should be less (j) Content 
should be aligned (k) Design shape should be there (l) Space should be 
less (m) The CTA button text should be in centre also the length should be 
little bit small as per bevespi. (n) The image is cutting in landscape mode 
(o) The marked CTA & its content should be in centre in landscape mode
Franklin bvespi SS: https://franklin.bevespi.com/how-to-use-bevespi-
inhaler

### PR DESCRIPTION
**Pull request by lansami**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #299 

Test URLs:
- Before: https://main--bevespi--hlxsites.hlx.page/how-to-use-bevespi-inhaler
- After: https://issue-299--bevespi--hlxsites.hlx.page/how-to-use-bevespi-inhaler

### CODE REVIEW

File: blocks/video/video.js [hunk 1]
```diff
@@ -6,20 +6,22 @@ export default function decorate(block) {
...
+        targetId: tagDivId,
+        wid: '_432521',
+        uiconf_id: 52784152,
+        flashvars: {},
+        cache_st: playerID,
+        entry_id: entryID,
+      });
     });
-  });
+  }, 3200);
```
Comment (dicagno) [inline blocks/video/video.js:26]: This is the approach we discussed and it's fine for now. For the future e might have a look at the LCP timeline tracking to start loading scripts right after page load.

**Review by dicagno — APPROVED** [review]
LGTM
